[theme]
base="light"
primaryColor="#6B4C3B"         # Rich earthy brown
backgroundColor="#E5D5B5"      # Light warm beige
secondaryBackgroundColor="#E9E1D4"  # Muted sandy tone
textColor="#6B4C3B"            # Dark woody brown
font="sans serif"